### ISSUE TITLE
Build Failure - generate-scr-description fails

### ISSUE THREAD

**Issue by HitmanInWis** [Adobe-Consulting-Services/acs-aem-samples#46]
I just pulled down the latest for this project and am trying to build with Java 8 and Maven 3.1.1, and I get the following error on build.  Any thoughts?

```
[ERROR] /Users/brett/Documents/clients/hs2/projects/acs-aem-samples/bundle/src/main/java/com/adobe/acs/samples/migration/impl/SampleContentReplicationHarnessImpl.java [1:1]: @Component : Class must have public default constructor: com.adobe.acs.samples.migration.impl.SampleContentReplicationHarnessImpl
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ACS AEM Samples - Reactor Project ................. SUCCESS [0.176s]
[INFO] ACS AEM Samples Bundle ............................ FAILURE [3.299s]
[INFO] ACS AEM Samples Content Package ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.231s
[INFO] Finished at: Thu Oct 06 08:48:37 CDT 2016
[INFO] Final Memory: 23M/324M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-scr-plugin:1.20.0:scr (generate-scr-descriptor) on project acs-aem-samples-bundle: SCR Descriptor parsing had failures (see log) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.felix:maven-scr-plugin:1.20.0:scr (generate-scr-descriptor) on project acs-aem-samples-bundle: SCR Descriptor parsing had failures (see log)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: SCR Descriptor parsing had failures (see log)
        at org.apache.felix.scrplugin.mojo.SCRDescriptorMojo.execute(SCRDescriptorMojo.java:251)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.felix.scrplugin.SCRDescriptorFailureException: SCR Descriptor parsing had failures (see log)
        at org.apache.felix.scrplugin.SCRDescriptorGenerator.execute(SCRDescriptorGenerator.java:223)
        at org.apache.felix.scrplugin.mojo.SCRDescriptorMojo.execute(SCRDescriptorMojo.java:237)
        ... 21 more
```

**Comment by AntonySagar** [comment]
Are you able to resolve this?

**Comment by HitmanInWis** [comment]
I honestly never looked much into it, sorry.  I took an alternate route to linking my sample package instead of adding into this project.

**Comment by AntonySagar** [comment]
Thank you.

**Comment by davidjgonzalez** [comment]
@HitmanInWis @AntonySagar are you just doing a `clean package`?  I tried a Java8 w maven 3.2.3 and it fine?

**Comment by HitmanInWis** [comment]
Strangely enough I tried building this morning again w/o even re-pulling from master, and it works fine.  I hadn't tried it since I submitted the ticket, so who knows...

Closing ticket.

**Comment by AntonySagar** [comment]
I'm able to resolve this by updating Uber-jar version with 6.2.0 SP1. Thanks.

**Comment by HitmanInWis** [comment]
I actually wonder if it was something with the first build failing, and a later build succeeding, unrelated to the uber-jar version, because I did not update my 6.2 version.

**Comment by Kk-krish** [comment]
i just downloaded and try to run the **`mvn clean`** ended up with the below error. and my maven version is **Apache Maven 3.1.1** and **Java version: 1.7.0_45**

> D:\AEM62-Proj\acs-aem-samples-master>mvn clean
> [INFO] Scanning for projects...
> Downloading: https://repo.adobe.com/nexus/content/groups/public/com/day/jcr/vault/content-package-maven-plugin/0.0.23/content-package-maven-plugin-0.0.23.pom
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]
> [ERROR]   The project com.adobe.acs:acs-aem-samples-content:1.0.0-SNAPSHOT (D:\AEM62-Proj\acs-aem-samples-master\content\pom.xml) has 2 errors
> [ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.0.23 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.day.jcr.vault:content-package-maven-plugin:jar:0.0.23: Could not transfer artifact com.day.jcr.vault:content-package-maven-plugin:pom:0.0.23 from/to adobe (https://repo.adobe.com/nexus/content/groups/public/): hostname in certificate didn't match: <repo.adobe.com> != <devedge.day.com> OR <devedge.day.com> -> [Help 2]
> [ERROR]     Unknown packaging: content-package @ line 39, column 16
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
